apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-service.fullname" . }}-secret
  labels:
    {{- include "hello-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasource-url: {{ .Values.secret.datasourceUrl | quote }}
  datasource-username: {{ .Values.secret.datasourceUsername | quote }}
  datasource-password: {{ .Values.secret.datasourcePassword | quote }}
